name: ki-aktienprognose-env
channels:
  - conda-forge
dependencies:
  # Core
  - python=3.13.7
  - pip=25.2

  # Jupyter
  - jupyterlab=4.4.5
  - ipykernel=6.30.1
  - ipython=9.4.0

  # Data & ML
  - pandas=2.3.2
  - numpy=2.3.0
  - scipy=1.16.0
  - scikit-learn=1.7.1
  - statsmodels=0.14.5
  - pmdarima=2.0.4
  - pandas-datareader=0.10.0

  # Plotting
  - matplotlib=3.10.5
  - seaborn=0.13.2
  - plotly=6.3.0

  # Utils
  - pyyaml=6.0.2
  - joblib=1.5.1
  - typing_extensions=4.15.0
  - ipywidgets=8.1.7

  # Pip
  - pip:
      - tensorflow==2.20.0
      - yfinance==0.2.65
      - pyarrow==21.0.0
      - tabulate==0.9.0
