name: ki-aktienprognose-env
channels:
  - conda-forge
dependencies:
  # Core
  - python=3.12.10
  - pip=25.2

  # Jupyter
  - jupyterlab=4.4.5
  - ipykernel=6.30.1
  - ipython=9.4.0

  # Data & ML
  - pandas=2.3.1
  - numpy=2.1.3
  - scipy=1.16.0
  - scikit-learn=1.7.1
  - statsmodels=0.14.5
  - pmdarima=2.0.4
  - pandas-datareader=0.10.0

  # Plotting
  - matplotlib=3.10.5
  - seaborn=0.13.2
  - plotly=6.2.0

  # Utils
  - pyyaml=6.0.2
  - joblib=1.5.1
  - typing_extensions=4.14.1
  - ipywidgets=8.0.6

  # Pip
  - pip:
      - tensorflow==2.19.0
      - yfinance==0.2.65
      - pyarrow==17.0.0
      - tabulate==0.9.0
