TECH_FEATURES:
- 12M_SMA_Return
- 3M_Momentum
- 3M_SMA_Return
- Return_Lag1
- Volatility_6M
MACRO_FEATURES:
- EPU_US
- FSI
- FedFunds_Delta_bps
- Gold_USD_oz
- Inflation_YoY_pct
- USD_per_EUR
- UnemploymentRate
- VIX
- WTI_Spot
